#!/usr/bin/env bash

set -euf -o pipefail

source "$SCRIPT_DIR/functions/history_chart"

history_file='/tmp/mem_history'

TYPE="${BLOCK_INSTANCE:-mem}"

mem_percent=$(awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	if (type == "swap") {
		free=swap_free/1024/1024
		used=(swap_total-swap_free)/1024/1024
		total=swap_total/1024/1024
	} else {
		free=mem_free/1024/1024
		used=(mem_total-mem_free)/1024/1024
		total=mem_total/1024/1024
	}

	pct=0
	if (total > 0) {
		pct=used/total*100
	}

	# short text
	printf("%.f", pct)
}
' /proc/meminfo)

history_graph "$history_file" "$mem_percent"
